include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_escaping_inner_quotes
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - cascade_invocations
    - close_sinks
    - combinators_ordering
    - conditional_uri_does_not_exist
    - deprecated_consistency
    - directives_ordering
    - discarded_futures
    - empty_constructor_bodies
    - eol_at_end_of_file
    - flutter_style_todos
    - join_return_with_assignment
    - library_names
    - literal_only_boolean_expressions
    - matching_super_parameters
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_literal_bool_comparisons
    - no_runtimeType_toString
    - no_self_assignments
    - noop_primitive_operations
    - omit_local_variable_types
    - package_prefixed_library_names
    - prefer_asserts_with_message
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_final_parameters
    - prefer_if_null_operators
    - prefer_relative_imports
    - prefer_single_quotes
    - require_trailing_commas
    - sized_box_shrink_expand
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - switch_on_type
    - test_types_in_equals
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_ignore
    - unnecessary_lambdas
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_unawaited
    - unreachable_from_main
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_null_aware_elements
    - use_raw_strings
    - use_string_buffers
    - use_to_and_as_if_applicable
    - use_truncating_division
